### ISSUE TITLE
Do you have plan to update to Swift 3?

### ISSUE THREAD

**Issue by vietstone-ng** [kiliankoe/iCal#1]
Hi, do you have plan to update this framework to Swift 3?

**Comment by kiliankoe** [comment]
Most definitely! Please be aware though that this project currently is more or less just a placeholder without a lot of functionality. It's also neither stable or fast.

This project was something I played around with several months ago. I hope on getting back to it at some point, but I wouldn't suggest using at this point, sry 😕 

Should you be very interested in this however, you're definitely welcome to fork it or submit PRs and we can see if we can make this something better suited for actual work than it currently is^^
