### ISSUE TITLE
Where can we find more ICS URL

### ISSUE THREAD

**Issue by SF-Simon** [kiliankoe/iCal#10]
I found a subscription URL in the calendar application of MacOS, which is about Chinese festivals.

Https://p19-calendars.icloud.com/holidays/cn_zh.ics

Is iCalKit tested for this subscription format?
Extra: can you help me find more festivals?

**Comment by kiliankoe** [comment]
Hi, sorry for the late reply!

At this point iCalKit has been tested very little and should not really be used for any actual projects. It's basically been a playground of sorts.

And sorry, I have no clue where else to find more info on Chinese festivals in the iCal format.
